name: Create File with Secrets

on:
  push:
    branches: [main]

jobs:
  create-secrets-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create Secrets File
        run: |
          echo "xyz=${{ secrets.xyz }}" > secrets.properties
          echo "abc=${{ secrets.abc }}" >> secrets.properties
          echo "mop=${{ secrets.mop }}" >> secrets.properties
        shell: bash

      - name: Store Secrets File as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: secrets-file
          path: secrets.properties
