name: Create File with Secrets

on:
  push:
    branches: [main]

jobs:
  create-secrets-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create Secrets File
        run: |
          echo "xyz=${{ secrets.xyz }}" > secrets.properties
          echo "abc=${{ secrets.abc }}" >> secrets.properties
          echo "mop=${{ secrets.mop }}" >> secrets.properties
        shell: bash

      - name: Store Secrets File as Artifact
        run: |
          while read -r line; do
          export "$line"
          done < secrets.properties
        shell: bash
        env:
         NO_LOG: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform plan
        id: plan
        run: terraform plan  