name: Create File with Secrets

on:
  push:
    branches: [main]

jobs:
  create-secrets-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create Secrets File
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" > secrets.properties
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> secrets.properties
        shell: bash

      - name: Debug Secrets File
        run: |
          cat secrets.properties

      - name: Load Secrets as Environment Variables
        run: |
           while read -r line; do
             export "$line"
           done < secrets.properties
           echo $AWS_ACCESS_KEY_ID
           echo $AWS_SECRET_ACCESS_KEY

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform plan
        id: plan
        run: terraform plan  